### ISSUE TITLE
Referenced field in config does not exist

### ISSUE THREAD

**Issue by UnlikelyLocation9** [FEEprojects/pycom-gps-logger#3]
The field DEV_ADDR is pulled from the config on line 123 of main.py, but the provided config.py example has no DEV_ADDR field.

Guessed defaults:
APPS_KEY = App Key from TTN
NWS_KEY = App EUI from TTN
DEV_ADDR = Device EUI from TTN

**Comment by pjb304** [comment]
Thanks for pointing this out, yes the authentication mode was changed to ABP in ac9594e1ab9c57ae34e9c46f6c9e547941a9be97 and I forgot to update the config template.  I've now put these fields in.
